package com.twitter.distributedlog.util;

/**
 * Sequencer generating transaction id.
 */
public interface Sequencer {

    /**
     * Return next transaction id generated by the sequencer.
     *
     * @return next transaction id generated by the sequencer.
     */
    long nextId();

}
