#!/bin/bash

BASEDIR=$(dirname "$0")
DISTRIBUTEDLOG_ROOT="${BASEDIR}/../.."

set -e
shopt -s dotglob

cd ${DISTRIBUTEDLOG_ROOT}
rm -rf distributedlog-service/lib
rm -rf distributedlog-internal/distributedlog-service-internal/lib
rm -rf dist/distributedlog-service*
mkdir -p dist/distributedlog-service/{bin,conf,lib}
mvn clean install -pl distributedlog-service,distributedlog-internal/distributedlog-service-internal -am -DskipTests
cp -r distributedlog-internal/distributedlog-service-internal/bin/* dist/distributedlog-service/bin
cp -r distributedlog-service/conf/* dist/distributedlog-service/conf
cp -r distributedlog-service/lib/* dist/distributedlog-service/lib
cp -r distributedlog-internal/distributedlog-service-internal/lib/* dist/distributedlog-service/lib
cp distributedlog-internal/distributedlog-service-internal/target/distributedlog-service-internal*.jar dist/distributedlog-service/lib
cp distributedlog-service/target/distributedlog-service-*.jar dist/distributedlog-service
cd dist
zip -r distributedlog-service.zip distributedlog-service >/dev/null
