#!/usr/bin/env bash
#
#/**
# * Copyright 2007 The Apache Software Foundation
# *
# * Licensed to the Apache Software Foundation (ASF) under one
# * or more contributor license agreements.  See the NOTICE file
# * distributed with this work for additional information
# * regarding copyright ownership.  The ASF licenses this file
# * to you under the Apache License, Version 2.0 (the
# * "License"); you may not use this file except in compliance
# * with the License.  You may obtain a copy of the License at
# *
# *     http://www.apache.org/licenses/LICENSE-2.0
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# */

set -e

DLOG_ROOT=$(git rev-parse --show-toplevel)

DLOG_HOME="${DLOG_ROOT}/distributedlog-service"

usage() {
  cat <<EOF
Usage: runner <command>
where command is one of:
  run                 Run distributedlog example
  help                This help message

or command is the full name of a class with a defined main() method.

Environment variables:
  DLOG_LOG_CONF        Log4j configuration file (default $DEFAULT_LOG_CONF)
  DLOG_EXTRA_OPTS      Extra options to be passed to the jvm
  DLOG_EXTRA_CLASSPATH Add extra paths to the dlog classpath

These variable can also be set in conf/dlogenv.sh
EOF
}

cd "${DLOG_ROOT}"
source ./scripts/common.sh

# get arguments
COMMAND="${1}"
shift

#Change to DLOG_HOME to support relative paths
cd "${DLOG_HOME}"

case "${COMMAND}" in
  run)
    java ${OPTS} $@
    ;;
  help)
    usage
    ;;
  *)
    usage
    exit 1
    ;;
esac
